import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ReactFlow,Background,Controls,Handle,Position,BaseEdge,EdgeLabelRenderer,MarkerType,useReactFlow,ReactFlowProvider,type NodeProps,type EdgeProps,type Node,type Edge} from '@xyflow/react';
import {ArrowLeft,ArrowRight,GitBranch,Activity,Maximize2,X,ArrowUpRight} from 'lucide-react';
import {phasePositions,summaries} from './calls.mjs';
import '@xyflow/react/dist/style.css';
import './graph.css';
type Call={id:string;number:number;sequence:number;source:string;target:string;phase:string;operation:string;timestamp:string;candidate?:string};
type Connection={id:string;source:string;target:string;calls:Call[]};
type Task={id:string;name:string;role:string;color:string};
type Model={calls:Call[];connections:Connection[]};
const time=(stamp:string)=>new Date(stamp).toLocaleTimeString('en-GB',{timeZone:'UTC',hour12:false});
function AgentRectangle({id,data}:NodeProps){const d=data as any;return <div className={`graph-agent ${d.highlight?'call-active':''}`} style={{'--node':d.color} as CSSProperties}>
  <Handle type="target" id="top" position={Position.Top}/><Handle type="target" id="left" position={Position.Left}/><Handle type="target" id="bottom" position={Position.Bottom}/>
  <button className="graph-agent-button" aria-label={`Summary: ${d.name}`} onFocus={e=>d.preview(id,e.currentTarget)} onBlur={d.leave} onMouseEnter={e=>d.preview(id,e.currentTarget)} onMouseLeave={d.leave} onClick={e=>d.preview(id,e.currentTarget,true)}><span className="graph-agent-role">{d.role}</span><strong>{d.name}</strong><span className="graph-agent-count">{d.inbound?`${d.inbound} received`:'Coordinates the run'}{d.outbound?` · ${d.outbound} sent`:''}</span></button>
  <Handle type="source" id="right" position={Position.Right}/><Handle type="source" id="out-bottom" position={Position.Bottom}/>
</div>;}
function CallEdge(props:EdgeProps){const d=props.data as any;const {sourceX:sx,sourceY:sy,targetX:tx,targetY:ty}=props;
  let path:string,lx:number,ly:number;
  if(props.source==='orchestrator'&&props.target==='reviewer'){path=`M ${sx} ${sy} H 198 V ${ty} H ${tx}`;lx=198;ly=ty-20;}
  else if(props.source==='orchestrator') {const p=(phasePositions as any)[props.target];const col=(p.x-230)/220;const lane=196+(p.y/140)*3+col*4;const y=p.y-25+col*3;path=`M ${sx} ${sy} H ${lane} V ${y} H ${tx} V ${ty}`;lx=tx;ly=y-12;}
  else {const p=(phasePositions as any)[props.source];const offset=d.workerLane;const y=p.y+93+offset*4;const lane=1090+offset*12;path=`M ${sx} ${sy} V ${y} H ${lane} V ${96-offset*5} H ${tx} V ${ty}`;lx=lane;ly=p.y+96;}
  return <><BaseEdge path={path} markerEnd={props.markerEnd} style={props.style}/><EdgeLabelRenderer><button aria-label={`${d.label}, ${d.calls.length} calls, ${d.sourceName} to ${d.targetName}`} className={`connection-badge nodrag nopan ${d.active?'active':''}`} style={{transform:`translate(-50%,-50%) translate(${lx}px,${ly}px)`}} onClick={()=>d.inspect(props.id)}>{d.label}</button></EdgeLabelRenderer></>;
}
const nodeTypes={agent:AgentRectangle},edgeTypes={call:CallEdge};
export function CallGraph(props:{tasks:Task[];model:Model;onBack:()=>void;onOpenTask:(id:string)=>void}){return <ReactFlowProvider><Graph {...props}/></ReactFlowProvider>;}
function Graph({tasks,model,onBack,onOpenTask}:{tasks:Task[];model:Model;onBack:()=>void;onOpenTask:(id:string)=>void}){
  const [cursor,setCursor]=useState<number|null>(null),[inspected,setInspected]=useState<string|null>(null),[page,setPage]=useState(0),[preview,setPreview]=useState<{id:string;x:number;y:number;pinned:boolean}|null>(null);
  const surface=useRef<HTMLDivElement>(null),closeTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const flow=useReactFlow();
  const call=cursor===null?null:model.calls[cursor];const group=model.connections.find(g=>g.id===inspected);const pageCount=group?Math.ceil(group.calls.length/4):0;
  const names=useMemo(()=>Object.fromEntries(tasks.map(t=>[t.id,t.name])),[tasks]);
  function closePreview(){clearTimeout(closeTimer.current);closeTimer.current=setTimeout(()=>setPreview(p=>p?.pinned?p:null),180);}
  function showPreview(id:string,element:HTMLElement,pinned=false){clearTimeout(closeTimer.current);const area=surface.current?.getBoundingClientRect();if(!area)return;const box=element.getBoundingClientRect();const factor=area.width&&surface.current!.clientWidth?area.width/surface.current!.clientWidth:1;const width=320;let x=(box.right-area.left)/factor+12;if(x+width>surface.current!.clientWidth)x=(box.left-area.left)/factor-width-12;setPreview({id,x:Math.max(12,x),y:Math.max(12,Math.min((box.top-area.top)/factor,surface.current!.clientHeight-250)),pinned});}
  useEffect(()=>()=>clearTimeout(closeTimer.current),[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='ArrowRight'){e.preventDefault();setCursor(i=>i===null?0:Math.min(model.calls.length-1,i+1));setInspected(null);}if(e.key==='ArrowLeft'){e.preventDefault();setCursor(i=>i===null?null:Math.max(0,i-1));setInspected(null);}if(e.key==='Escape'){setPreview(null);setInspected(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[model]);
  const nodes:Node[]=tasks.map(t=>({id:t.id,type:'agent',position:(phasePositions as any)[t.id],data:{...t,highlight:call?.source===t.id||call?.target===t.id,inbound:model.calls.filter(c=>c.target===t.id).length,outbound:model.calls.filter(c=>c.source===t.id).length,preview:showPreview,leave:closePreview}}));
  const edges:Edge[]=model.connections.map(g=>{const active=call?.source===g.source&&call.target===g.target;return {id:g.id,source:g.source,target:g.target,sourceHandle:g.source==='orchestrator'?'right':'out-bottom',targetHandle:g.target==='reviewer'?'left':g.target==='worker'?'bottom':'top',type:'call',markerEnd:{type:MarkerType.ArrowClosed,color:active?'#f5f5f5':g.target==='worker'?'#67caff':g.target==='reviewer'?'#f3c46b':'#7d7d7d'},style:{stroke:active?'#f5f5f5':g.target==='worker'?'#67caff':g.target==='reviewer'?'#f3c46b':'#686868',strokeWidth:active?2.3:1,opacity:call&&!active?0.25:0.7},data:{...g,active,label:`#${String(g.calls[0].number).padStart(2,'0')}${g.calls.length>1?` · ×${g.calls.length}`:''}`,sourceName:names[g.source],targetName:names[g.target],workerLane:['model_search','evaluation','abstention'].indexOf(g.source),inspect:(id:string)=>{setInspected(id);setPage(0);setPreview(null);}}};});
  const task=tasks.find(t=>t.id===preview?.id);const fit=()=>flow.fitView({padding:0.13,duration:0});
  return <div className="graph-page"><header className="graph-header"><div><span className="eyebrow">PATHMNIST · SEED 42</span><h1>Agent call graph</h1><p>One agent per box. Every recorded invocation in sequence.</p></div><div className="graph-header-actions"><span>{model.calls.length} calls <span className="graph-stat-divider">/</span> {tasks.length} agents</span><button onClick={fit}><Maximize2 size={15}/> Fit graph</button><button onClick={onBack}><ArrowLeft size={15}/> Back to dashboard</button></div></header>
    <div className="graph-surface" ref={surface}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} fitView fitViewOptions={{padding:0.13}} minZoom={0.3} maxZoom={1.8} nodesDraggable={false} nodesConnectable={false} elementsSelectable={false} onPaneClick={()=>{setPreview(null);setInspected(null);}}><Background color="#242424" gap={24}/><Controls showInteractive={false}/></ReactFlow>
      <div className="graph-legend"><span><i style={{background:'#999'}}/> Task dispatch</span><span><i style={{background:'#f3c46b'}}/> Independent review</span><span><i style={{background:'#67caff'}}/> Worker execution</span><span># = first call · × = total passes</span></div>
      {task&&preview&&<aside className="agent-popover" role="dialog" aria-label={`${task.name} summary`} style={{left:preview.x,top:preview.y,'--node':task.color} as CSSProperties} onMouseEnter={()=>clearTimeout(closeTimer.current)} onMouseLeave={closePreview} onFocus={()=>clearTimeout(closeTimer.current)} onBlur={closePreview}><div><span className="eyebrow">DECISIONS & CONTRIBUTION</span><button aria-label="Close agent summary" onClick={()=>setPreview(null)}><X size={13}/></button></div><h2>{task.name}</h2><ul>{(summaries as any)[task.id].map((text:string)=><li key={text}>{text}</li>)}</ul><button className="open-task" onClick={()=>onOpenTask(task.id)}>Explore this task <ArrowUpRight size={14}/></button></aside>}
      {group&&<aside className="connection-popover" aria-label="Connection passes"><div className="connection-title"><span className="eyebrow">{group.calls.length} RECORDED {group.calls.length===1?'PASS':'PASSES'}</span><button aria-label="Close connection passes" onClick={()=>setInspected(null)}><X size={14}/></button></div><h2>{names[group.source]} <ArrowRight size={14}/> {names[group.target]}</h2><div className="connection-calls">{group.calls.slice(page*4,page*4+4).map(c=><button key={c.id} onClick={()=>{setCursor(c.number-1);setInspected(null);}}><span className="pass-number">#{String(c.number).padStart(2,'0')}</span><span><strong>{c.operation}</strong><small>{names[c.phase]}{c.candidate?` · Trial ${Number(c.candidate.split('t').at(-1))}`:''}</small></span><time>{time(c.timestamp)}</time></button>)}</div><nav><button aria-label="Previous connection page" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={13}/></button><span>{page+1} / {pageCount}</span><button aria-label="Next connection page" disabled={page===pageCount-1} onClick={()=>setPage(p=>p+1)}><ArrowRight size={13}/></button></nav></aside>}
    </div>
    <div className="call-navigation"><button aria-label="Previous call" disabled={cursor===null||cursor===0} onClick={()=>{setCursor(i=>i===null?null:i-1);setInspected(null);}}><ArrowLeft size={16}/> Previous call</button><div className="call-readout" aria-live="polite">{call?<><span className="call-index">Call {call.number} of {model.calls.length}</span><strong>{names[call.source]} <ArrowRight size={13}/> {names[call.target]}</strong><small>{call.operation} · {names[call.phase]} · {time(call.timestamp)} UTC</small></>:<><span className="call-index">COMPLETE GRAPH</span><strong>Explore the team, or follow the calls with the arrows.</strong><small>Hover an agent for its decisions. Select a numbered connection to inspect its passes.</small></>}</div><button aria-label="Next call" disabled={cursor===model.calls.length-1} onClick={()=>{setCursor(i=>i===null?0:i+1);setInspected(null);}}>Next call <ArrowRight size={16}/></button><button className="overview-button" onClick={()=>{setCursor(null);setInspected(null);setPreview(null);fit();}}><GitBranch size={15}/> Overview</button></div>
    <footer><span><Activity size={12}/> Documented task, reviewer and worker invocations</span><span>No direct agent-to-agent calls are inferred.</span><span>Arrow keys to navigate · Escape to close summaries</span></footer>
  </div>;
}
