export const percent=(n,digits=2)=>`${(n*100).toFixed(digits)}%`;
const number=n=>n.toLocaleString('en-US');
const page=(title,goal,choice,outcome,extra={})=>({title,goal,choice,outcome,...extra});
const table=(columns,rows)=>({columns,rows});
export function readRun(archive) {
  if(archive?.format!=='agent-run-explorer-v1'||!Array.isArray(archive.events))throw Error('The PathMNIST run could not be read.');
  const records={};const sources={};
  for(const event of [...archive.events].sort((a,b)=>a.sequence-b.sequence)) {
    if(event.event==='artefact_written'&&archive.files?.[event.path]) {records[event.artefact]=archive.files[event.path].payload;sources[event.artefact]=event.path;}
  }
  for(const key of ['dataset_manifest','data_profile','data_audit_report','search_report','best_configuration','selected_training_result','evaluation_report','abstention_report','acceptance_report'])if(!records[key])throw Error(`The bundled run is incomplete (${key}).`);
  return {records,sources,events:archive.events,decisions:archive.events.filter(e=>e.event==='llm_decision'),name:archive.name};
}
export function buildDashboard(archive) {
  const run=readRun(archive),r=run.records,d=r.dataset_manifest,p=r.data_profile,s=r.search_report,b=r.best_configuration,t=r.selected_training_result,e=r.evaluation_report,a=r.abstention_report,c=r.acceptance_report;
  const task=(id,name,role,color,status,pages)=>({id,name,role,color,status,pages});
  const tasks=[
    task('ingestion','Data ingestion','Dataset preparation','#46e0c1','Passed',[
      page('A complete, verified dataset','Load the official PathMNIST dataset for nine-class tissue classification.','Use the full 28 × 28 RGB dataset and preserve its official train, validation and test partitions.','The run loaded all samples without subsampling. Integrity checks confirmed that the dataset matched the expected release.',{table:table(['Partition','Images','Purpose'],[['Training',number(d.loaded_split_sizes.train),'Fit model weights'],['Validation',number(d.loaded_split_sizes.val),'Select models and calibrate'],['Test',number(d.loaded_split_sizes.test),'Final held-out evaluation']]),note:'The test images originate from a separate center. This becomes important when interpreting generalization.'}),
      page('Proceed after integrity review','Check that the experiment starts with a trustworthy dataset.','Verify archive integrity, image shape, class count and official split sizes before downstream work.','The reviewer permitted ingestion to proceed. Worker isolation was noted as an operational limitation, without invalidating the data checks.',{table:table(['Check','Result'],[['Classes',String(d.n_classes)],['Image shape','28 × 28 × 3'],['Official dataset used','100%'],['Subsampling','None'],['Test provenance','Different clinical center']])})
    ]),
    task('profiling','Data profiler','Dataset understanding','#53d9a9','Passed',[
      page('Understand class balance and ambiguity','Identify dataset characteristics that should shape modeling choices.','Profile training and validation only; examine class counts, image quality and potential confusion between tissue types.','No duplicate training images or blank images were reported. Class imbalance was mild, while small image size made some tissue distinctions potentially ambiguous.',{table:table(['Statistic','Observed value'],[['Images profiled',number(p.samples_profiled)],['Training duplicates',String(p.duplicate_train_samples)],['Blank images',percent(p.blank_image_fraction)],['Largest / smallest train class',p.imbalance_ratio.toFixed(2)+'×'],['Smallest train class',number(Math.min(...p.class_counts.train))],['Largest train class',number(Math.max(...p.class_counts.train))]])}),
      page('Potential confusion was a hypothesis','Anticipate difficult tissue distinctions without looking at test results.','Flag fibrous stroma versus muscle, low-structure background versus debris, and mixed glandular tissues as possible risks.','These were modeling hypotheses based on low-resolution tissue appearance. Later evaluation confirmed particularly weak stroma performance; it did not prove every predicted confusion pattern.',{table:table(['Potential overlap','Why it was considered'],[['Stroma / smooth muscle','Fibrous or spindle-cell appearance'],['Background / debris / mucus','Low-structure image regions'],['Normal mucosa / adenocarcinoma','Mixed glandular architecture']]),note:'Train and validation class proportions were closely matched. This alone cannot establish cross-center robustness.'})
    ]),
    task('prior_art','Literature researcher','Research hypotheses','#ac8bff','Warning',[
      page('Literature guided the starting ideas','Form plausible architecture and preprocessing hypotheses for small histology images.','Use three curated literature excerpts to motivate local texture modeling, compact attention and class-aware training.','The ideas were traceable to cited material, but no live retrieval occurred. Specific design inferences remained hypotheses to test.',{table:table(['Research claim','Evidence strength'],[['Compact models on small inputs','Motivated by curated excerpts'],['Convolutional tokenization','Design hypothesis'],['Class-weighted loss','Local heuristic; weak citation support'],['Live web retrieval','Not performed']]),note:'A citation established traceability; it did not independently validate patch size, architecture fit or performance.'}),
      page('Proposals did not become new implementations','Separate available operations from new architectural extensions.','Propose a convolution-stem transformer and tissue flips. Keep genuinely new extensions behind independent review.','The new architecture remained pending review. Horizontal and vertical flips were already built-in operations, so their extra gate entry was redundant.',{table:table(['Proposal','Disposition'],[['Convolution-stem transformer','Pending independent review'],['Horizontal / vertical flips','Built-in operations; extra gate redundant'],['Implemented search candidates','Existing model families']])})
    ]),
    task('preprocessing','Representation designer','Input preparation','#46e0c1','Warning',[
      page('Normalize using training data only','Prepare comparable, stable inputs without using held-out statistics.','Standardize RGB channels with training-only means and standard deviations; apply six augmentation operations only during training.','The representation combined geometric transforms with brightness and contrast changes. Its effect was not isolated by an ablation study.',{table:table(['Channel','Mean','Standard deviation'],['Red','Green','Blue'].map((name,i)=>[name,p.train_channel_mean_unit[i].toFixed(4),p.train_channel_std_unit[i].toFixed(4)])),note:'Training augmentations: horizontal flip, vertical flip, 90° and 180° rotation, brightness and contrast.'}),
      page('The preprocessing explanation needed correction','Keep the representation description aligned with the final model.','Retain valid train-only normalization and augmentations, while flagging outdated transformer-specific justification.','The final report acknowledged that the selected model was ResNet18. A confusing token-count explanation was also identified; neither issue changed the input operations.',{note:'A 7 × 7 spatial grid contains 49 tokens. A 28 × 28 image split into 7 × 7 patches instead produces 16 tokens; these descriptions must not be conflated.'})
    ]),
    task('data_audit','Data auditor','Leakage checks','#f3c46b','Passed',[
      page('Training was cleared by the leakage audit','Confirm correct splits, inputs and training-only preprocessing before any model fitting.','Audit indices, labels, image shapes, pixel values, normalization statistics and train–validation disjointness.','All eleven checks passed. No training image overlapped validation, and the audit did not inspect the held-out test set.',{table:table(['Audit item','Result'],[['Checks passed',`${Object.values(r.data_audit_report.checks).filter(Boolean).length} / ${Object.keys(r.data_audit_report.checks).length}`],['Train–validation overlap',String(r.data_audit_report.train_validation_overlap)],['Training-only statistics','Passed'],['Official split','Passed'],['Test inspected during audit',r.data_audit_report.test_inspected?'Yes':'No']])})
    ]),
    task('architecture_research','Architecture researcher','Candidate strategy','#ac8bff','Warning',[
      page('Start with attention, compare against convolutions','Choose models whose input processing suits 28 × 28 histology patches.','Prioritize a compact transformer with convolutional tokenization, explore multiple spatial scales, and test ResNet18 as a strong CNN comparator.','Search ultimately explored compact transformer, multiscale transformer and ResNet18. Four other available families were not evaluated.',{table:table(['Candidate family','Reason to test'],[['Compact transformer','Local tokenization followed by attention'],['Multiscale transformer','Combine fine and coarse spatial information'],['ResNet18','Local texture hierarchy and residual learning']]),note:'The architecture fit arguments were hypotheses. Only validation experiments supplied performance evidence.'}),
      page('Available operations were clarified by review','Avoid treating existing framework features as unapproved extensions.','Distinguish the built-in compact tokenizer and tissue augmentations from the proposed new architecture.','Review clarified that built-in augmentations could be used without an extension approval. A pending new proposal did not block existing primitives.',{note:'Architecture and optimization settings changed together across trials, so the search does not isolate the causal benefit of any one setting.'})
    ]),
    task('model_search','Autonomous search','Eight experiments','#7aa8ff','Selected',[
      page('Eight experiments, one validation-selected model','Compare candidate designs while keeping test metrics out of selection.','Try five transformer configurations, then three ResNet18 variants. Rank saved checkpoints using validation accuracy tolerance and macro-F1.','Trial 7, the tuned ResNet18, was selected. All eight training trials completed without failures.',{table:table(['Trial','Model','Checkpoint acc.','Macro F1','Curve peak'],s.validation_trials.map((v,i)=>[`${i+1}${v.candidate_id===s.selected_candidate_id?' ★':''}`,['Compact · width 128','Multiscale','Compact · width 256','Compact · depth 6','Compact · depth 8','ResNet18','ResNet18 tuned','ResNet18 less regularized'][i],percent(v.checkpoint_accuracy,3),v.checkpoint_macro_f1.toFixed(4),percent(v.curve_max_accuracy,3)])),note:'Checkpoint accuracy and the highest point on the training curve are different statistics. Selection used the saved checkpoint.'}),
      ...s.validation_trials.map((v,i)=>{
        const experiments=[
          ['Try compact attention','Use a compact transformer with width 128 and depth 4 to test local tokenization followed by attention.','This established the first validation benchmark. There was no CNN comparison yet.'],
          ['Try multiple spatial scales','Combine patch scales 2, 4 and 7 to test whether joint fine/coarse attention improves tissue discrimination.','The saved checkpoint underperformed Trial 1 and took longer to train. Multiscale superiority was not supported.'],
          ['Increase transformer width','Raise width from 128 to 256; also lower learning rate and label smoothing.','The checkpoint improved over Trial 1. Because several settings changed, the gain cannot be attributed to width alone.'],
          ['Increase transformer depth','Use six blocks and adjust learning rate, dropout and patience to explore a larger transformer.','This was the best saved transformer checkpoint. The run did not isolate depth as the only cause of the gain.'],
          ['Test an even deeper transformer','Increase to eight blocks, increase dropout and extend the training budget.','The saved result fell below the six-block variant. Increasing depth did not consistently improve these tested configurations.'],
          ['Compare a convolutional model','Test ResNet18 with a small-image stem, residual feature hierarchy and a different optimization configuration.','Its checkpoint exceeded every tested transformer. This supported choosing a CNN within this search, not a universal CNN advantage.'],
          ['Refine the ResNet18','Lower learning rate to 0.0002 and label smoothing to 0.05, with a 50-epoch budget and patience 12.','This produced the selected checkpoint. Its curve peak did not exceed the previous CNN’s curve peak, despite a better saved-checkpoint score.'],
          ['Reduce regularization further','Lower dropout, weight decay, label smoothing and learning rate, and extend the budget to 60 epochs.','The saved checkpoint underperformed Trials 6 and 7. The combined change did not improve this run; it does not isolate a dropout effect.']
        ];
        const [title,choice,outcome]=experiments[i];
        return page(`Trial ${i+1} · ${title}`,'Test the next modeling hypothesis using validation data only.',choice,outcome,{trial:i+1,table:table(['Statistic','Value'],[['Checkpoint accuracy',percent(v.checkpoint_accuracy,3)],['Checkpoint macro F1',v.checkpoint_macro_f1.toFixed(4)],['Maximum curve accuracy',percent(v.curve_max_accuracy,3)],['Saved checkpoint epoch',String(v.best_epoch)],['Training duration',`${(v.duration_seconds/60).toFixed(1)} min`]])});
      }),
      page('Select Trial 7 and stop on an operational constraint','Finalize a validated configuration without using test results.','Keep the tuned ResNet18. When the ninth proposal failed validation, recover with a finish-search decision because new experiments were disallowed and no candidate could be resumed.','Search ended with eight completed trials and no failed training trials. The failed proposal was a decision attempt, not a ninth experiment.',{note:'Stopping was imposed by process constraints. It did not demonstrate a performance ceiling or exhaustive family coverage.'})
    ]),
    task('training','Model trainer','Selected configuration','#7aa8ff','Warning',[
      page('The selected CNN and optimization settings','Preserve the configuration selected by validation.','Use ResNet18 with base width 64 and head dropout 0.3, AdamW, class weighting, label smoothing and a cosine schedule.','The architecture was a CNN. Generic transformer fields were inactive; the fixed ResNet18 topology ignored the supplied depth value.',{table:table(['Setting','Effective value'],[['Network','ResNet18 · width 64'],['Head dropout',String(b.train_config.generated_bundle.parameters.dropout)],['Optimizer / learning rate',`${b.train_config.optimizer.toUpperCase()} / ${b.train_config.lr}`],['Weight decay / label smoothing',`${b.train_config.weight_decay} / ${b.train_config.label_smoothing}`],['Batch size / class weighting',`${b.train_config.batch_size} / enabled`],['Scheduler / maximum epochs',`Cosine / ${b.train_config.epochs}`]])}),
      page('Early stopping retained a near-peak checkpoint','Control convergence using the monitored validation score.','Require an improvement above the configured minimum change before replacing the best checkpoint and resetting patience.','Training ended after 29 epochs with the checkpoint from epoch 17. A later score was slightly higher, but the 0.0002 increase was below the 0.001 minimum change.',{chart:t.history,table:table(['Statistic','Value'],[['Epochs completed',String(t.epochs_completed)],['Saved checkpoint epoch',String(t.best_epoch)],['Saved accuracy',percent(t.best_val_accuracy,3)],['Curve maximum',percent(s.validation_trials[6].curve_max_accuracy,3)],['Patience / minimum change',`${b.train_config.early_stopping_patience} / ${b.train_config.early_stopping_min_delta}`]]),note:'The reviewer flagged the apparent score mismatch. The minimum-change rule explains why “best checkpoint” can differ from the curve maximum.'})
    ]),
    task('evaluation','Evaluator','Held-out performance','#46e0c1','Warning',[
      page('Strong validation, lower separate-center accuracy','Measure the selected model on the untouched test split.','Evaluate the frozen validation-selected checkpoint on all 7,180 test images and compute aggregate and class-level metrics.','Accuracy fell by 7.81 percentage points from validation to test. The different-center provenance is relevant, but this run does not identify a specific causal mechanism.',{table:table(['Metric','Validation checkpoint','Held-out test'],[['Accuracy',percent(b.validation_accuracy),percent(e.accuracy)],['Macro F1',b.validation_macro_f1.toFixed(4),e.macro_f1.toFixed(4)],['Balanced accuracy','—',percent(e.balanced_accuracy)],['Macro ROC-AUC','—',e.roc_auc_ovr_macro.toFixed(4)],['Accuracy 95% interval','—',`${percent(e.accuracy_ci95_low)}–${percent(e.accuracy_ci95_high)}`]])}),
      page('Class-level results expose the weak points','Check whether aggregate accuracy hides uneven tissue performance.','Compare precision, recall and F1 across all nine classes.','Cancer-associated stroma was weakest, followed by smooth muscle. Background and lymphocytes had perfect recall, but still received false-positive predictions.',{table:table(['Tissue class','Precision','Recall','F1','Images'],e.per_class.map(v=>[v.name==='colorectal adenocarcinoma epithelium'?'Colorectal adenocarcinoma':v.name,percent(v.precision,1),percent(v.recall,1),v.f1.toFixed(3),number(v.support)])),note:'Stroma recall was only 52.0%; aggregate accuracy alone would obscure this limitation.'}),
      page('Stroma errors were the clearest weakness','Describe observed confusions instead of attributing them to an untested cause.','Inspect where the 421 stroma images were classified and verify the lymphocyte false-positive count.','Only 219 stroma images were correct; 202 were missed. Lymphocytes received 28 false positives, a count corrected during report revision.',{table:table(['Stroma prediction','Images'],[['Correct stroma',String(e.confusion_matrix[7][7])],['Smooth muscle',String(e.confusion_matrix[7][5])],['Colorectal adenocarcinoma',String(e.confusion_matrix[7][8])],['Debris',String(e.confusion_matrix[7][2])],['Other tissue classes',String(421-219-70-59-55)]]),note:'These counts establish the error pattern. The experiment does not prove whether staining, resolution, architecture or another factor caused it.'})
    ]),
    task('abstention','Uncertainty analyst','Coverage and review','#f3c46b','Warning',[
      page('Abstention improves accuracy on accepted images','Identify uncertain predictions for human review.','Calibrate an entropy-based threshold on validation to target 80% coverage; apply that same threshold to test.','Test coverage was 69.28%, with 97.59% accuracy among accepted images. The system routed 2,206 test images to human review.',{table:table(['Statistic','Result'],[['Target validation coverage',percent(a.target_validation_coverage)],['Achieved validation coverage',percent(a.validation_coverage)],['Achieved test coverage',percent(a.test_coverage)],['Accuracy on covered test images',percent(a.accuracy_on_covered)],['Abstention / human review',`${percent(a.abstain_rate)} / ${number(a.human_review_count)}`]]),note:'Improved accuracy on the covered subset comes with reduced coverage. It is not an improvement over all test images.'}),
      page('The validation threshold did not transfer unchanged','Compare coverage and error risk at different validation-calibrated thresholds.','Measure accepted-sample error rates on both validation and test without recalibrating from test labels.','Every threshold accepted a smaller fraction of test images. At the 80% target, test coverage was about 10.7 points below validation.',{table:table(['Val. target','Val. coverage','Val. risk','Test coverage','Test risk'],a.risk_coverage_curve.map(v=>[percent(v.target_validation_coverage,0),percent(v.validation_coverage),percent(v.validation_risk),percent(v.test_coverage),percent(v.test_risk)])),note:'Risk is the error rate among accepted predictions. Coverage is the fraction accepted.'}),
      page('OOD detection passed a narrow stress test','Test whether confidence scores flag controlled pixel corruption.','Apply Gaussian noise at three severity levels and compare confidence-based detectors.','Predictive entropy achieved mean test AUROC 0.9434. All scenarios passed the configured thresholds, within this corruption-only evaluation.',{table:table(['Noise σ','Validation AUROC','Test AUROC','False accept rate'],a.ood_scenarios.filter(v=>v.score==='predictive_entropy').map(v=>[v.corruption.split('_').at(-1),v.validation_auroc.toFixed(4),v.test_auroc.toFixed(4),percent(v.test_false_accept_rate)])),note:'Gaussian noise does not reproduce scanner, staining or preparation changes. Passing this proxy does not establish robustness to those shifts.'})
    ]),
    task('reporting','Report writer','Findings and revision','#ac8bff','Revised',[
      page('The reviewer requested two concrete corrections','Turn the experiment into an accurate account of results and limitations.','Revise the initial report to acknowledge the stale transformer-specific preprocessing explanation and correct the lymphocyte false-positive count.','The revised report described the selected model as ResNet18 and reported 28 lymphocyte false positives. The reviewer accepted the revised narrative with warnings.',{table:table(['Issue','Final correction'],[['Architecture description','ResNet18; outdated transformer rationale acknowledged'],['Lymphocyte false positives','28, from 5 mucosa + 2 stroma + 21 cancer images'],['Meaning of search stop','Operational constraint, not a proven ceiling']])}),
      page('The supported conclusion is deliberately bounded','Summarize what this experiment established.','Recommend the tuned ResNet18 among the tested configurations while foregrounding test-center transfer, stroma weakness and abstention coverage.','The run completed with warnings. Baseline comparison, representation ablations and cross-seed variance were not established.',{table:table(['Conclusion','Evidence boundary'],[['ResNet18 wins this search','Eight tested configurations, validation-selected'],['Separate-center test accuracy','91.78%, one seed'],['Human review workload','30.72% of test images'],['Robustness claim','Gaussian corruption proxy only']])})
    ]),
    task('orchestrator','Orchestrator','Run coordination','#ff85b3','Warning',[
      page('Coordinate stages and independent reviews','Move the experiment through a controlled sequence of tasks.','Dispatch each stage, require its reviewer decision, preserve the selected checkpoint and handle the reporting retry.','The run completed with warnings. Reporting was attempted twice; the search recovered from one failed decision attempt and still completed all eight trials.',{table:table(['Coordination statistic','Recorded count'],[['Distinct task phases','11'],['Stage attempts',String(run.events.filter(v=>v.event==='stage_started').length)],['Review gates',String(run.events.filter(v=>v.event==='review_gate').length)],['LLM decisions',String(run.decisions.length)],['Failed decision attempts',String(run.decisions.filter(v=>v.status==='failed').length)]])}),
      page('Completion did not mean acceptance readiness','Assess the full run against the project’s acceptance requirements.','Keep successful execution separate from completeness of validation evidence and independent signoff.','Acceptance readiness and technical completeness were both false. Missing comparisons, ablations, multiple seeds and unresolved mitigations prevented a stronger acceptance conclusion.',{table:table(['Acceptance requirement','State'],c.criteria.filter(v=>v.status==='failed').map(v=>[{'WP2_WEB_RETRIEVAL':'Live literature retrieval','WP4_BASELINE_COMPARISON':'Separate baseline comparison','WP4_REPRESENTATION_ABLATIONS':'Representation ablations','WP4_FROZEN_CONFIGURATION_SEED_VARIANCE':'Frozen configuration across ≥3 seeds','WP6_APPROVED_RISK_MITIGATIONS':'Approved unresolved-risk mitigations'}[v.requirement]??v.requirement,v.status]))}),
      page('Independent evidence remained pending','Identify requirements that were neither completed nor demonstrated by this run.','Separate pending validation evidence from the criteria that explicitly failed.','Fault-injection measurement, retraining replay and independent demonstration/signoff remained pending.',{table:table(['Pending requirement','State'],[['Measured fault detection','Pending'],['Full retraining replay','Pending'],['Independent demonstration and signoff','Pending']]),note:'A complete transcript supports traceability, but it does not prove repeated training reproduces the same predictions.'})
    ]),
    task('reviewer','Independent reviewer','Consistency and corrections','#f3c46b','Warning',[
      page('Review decisions throughout the run','Check that stage results and explanations match the available evidence.','Review data integrity, literature support, preprocessing, search selection, training, evaluation, uncertainty and reporting.','Reviews permitted progress while retaining warnings. The report was explicitly revised rather than silently ignoring identified mistakes.',{table:table(['Review finding','Disposition'],[['Data integrity and leakage','Passed'],['Curated literature vs live retrieval','Limitation retained'],['Selection uses validation only','Confirmed'],['Stale architecture explanation','Acknowledged in revised report'],['Lymphocyte false-positive count','Corrected to 28']])}),
      page('Reviewer statements also need interpretation','Distinguish checked facts from stronger claims in review comments.','Read the checkpoint discrepancy alongside the training minimum-change rule, and distinguish combined trial changes from isolated effects.','The checkpoint mismatch is consistent with the configured improvement threshold. Trial 8 changed several settings; its poorer result cannot establish that dropout alone was responsible.',{note:'Review improved the report, but its comments are not an independent controlled experiment. One seed and no ablations limit causal conclusions.'})
    ]),
    task('worker','Experiment worker','Local execution','#67caff','Completed',[
      page('Execute training and prediction jobs locally','Run candidate experiments and evaluation jobs outside the agent decision loop.','Use local subprocess workers for model fitting and prediction, with CUDA configured for training.','Thirty-two local jobs completed, including eight candidate training trials. A job count is not a count of distinct model experiments.',{table:table(['Execution statistic','Result'],[['Local jobs completed',String(run.events.filter(v=>v.event==='local_job_completed').length)],['Model trials completed',String(s.completed_trials)],['Failed model trials',String(s.failed_trials)],['Training device',t.device],['Execution mode','Local subprocess'],['Enforced container isolation','No']]),note:'Recorded hashes and seed 42 support traceability. Enforced worker isolation and independent retraining reproducibility were not demonstrated.'})
    ])
  ];
  // Internal source mapping is for validation only; the dashboard never renders raw evidence.
  const evidenceKeys={ingestion:['dataset_manifest','anomaly_ingestion'],profiling:['data_profile','anomaly_profiling'],prior_art:['prior_art_brief','extension_gate_report','anomaly_prior_art'],preprocessing:['representation_plan','data_profile','anomaly_preprocessing','report_summary'],data_audit:['data_audit_report','anomaly_data_audit'],architecture_research:['architecture_research','anomaly_architecture_research'],model_search:['search_report','best_configuration','anomaly_model_search','autonomous_action_0009'],training:['best_configuration','selected_training_result','anomaly_training'],evaluation:['evaluation_report','anomaly_evaluation'],abstention:['abstention_report','anomaly_abstention'],reporting:['report_summary','anomaly_reporting','review_response_reporting'],orchestrator:['execution_status','acceptance_report'],reviewer:Object.keys(run.sources).filter(key=>key.startsWith('anomaly_')),worker:['worker_evidence','selected_training_result','search_report']};
  for(const task of tasks)for(const step of task.pages){step.sources=evidenceKeys[task.id].map(key=>run.sources[key]).filter(Boolean);if(step.trial)step.sources.push(run.sources[`trial_${String(step.trial).padStart(4,'0')}`]);step.decisionSequences=[];}
  for(const decision of run.decisions){
    let id=decision.stage.replace(/^review\./,'').split('.')[0];
    if(id==='autonomous_search')id='model_search';
    const target=tasks.find(task=>task.id===id);if(!target)throw Error(`Unmapped decision: ${decision.stage}`);
    let step=target.pages[0];
    if(decision.stage.startsWith('autonomous_search.action_')) {const n=Number(decision.stage.split('_').at(-1));step=target.pages[n<=8?n:target.pages.length-1];}
    else if(decision.stage.startsWith('autonomous_search.recovery'))step=target.pages.at(-1);
    else if(decision.stage.startsWith('review.'))step=target.pages.at(-1);
    else if(id==='reporting')step=target.pages[0];
    step.decisionSequences.push(decision.sequence);
  }
  // Briefs, tables and charts each occupy one screen. No content relies on scrolling.
  for(const task of tasks)task.pages=task.pages.flatMap(step=>[
    {...step,table:undefined,chart:undefined,view:'summary'},
    ...(step.table?[{...step,chart:undefined,note:undefined,decisionSequences:[],view:'statistics'}]:[]),
    ...(step.chart?[{...step,table:undefined,decisionSequences:[],view:'chart'}]:[])
  ]);
  return {tasks,runName:run.name,stats:{decisions:run.decisions.length,trials:s.completed_trials,validation:b.validation_accuracy,test:e.accuracy,macroF1:e.macro_f1,review:a.human_review_count},status:'Completed with warnings',selected:'ResNet18 tuned',seed:42};
}
