import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,Activity,Database,Microscope,BookOpen,SlidersHorizontal,ShieldCheck,Layers,FlaskConical,Cpu,ChartNoAxesCombined,Eye,FileCheck2,GitBranch,Check,TriangleAlert,ChevronRight} from 'lucide-react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {buildDashboard,percent} from './dashboard.mjs';
import {buildCalls} from './calls.mjs';
import {CallGraph} from './CallGraph';
import './style.css';
interface Step {title:string;goal:string;choice:string;outcome:string;note?:string;table?:{columns:string[];rows:string[][]};chart?:Record<string,number>[];view?:'summary'|'statistics'|'chart'}
interface Task {id:string;name:string;role:string;color:string;status:string;pages:Step[]}
interface Dashboard {tasks:Task[];runName:string;stats:{decisions:number;trials:number;validation:number;test:number;macroF1:number;review:number};status:string;selected:string;seed:number}
const icons:Record<string,typeof Activity>={ingestion:Database,profiling:Microscope,prior_art:BookOpen,preprocessing:SlidersHorizontal,data_audit:ShieldCheck,architecture_research:Layers,model_search:FlaskConical,training:Cpu,evaluation:ChartNoAxesCombined,abstention:Eye,reporting:FileCheck2,orchestrator:GitBranch,reviewer:ShieldCheck,worker:Cpu};
const contributionStatus=(status:string)=>({Warning:'Reviewed',Revised:'Refined',Passed:'Validated'}[status]??status);
export function App(){
  const [dashboard,setDashboard]=useState<Dashboard|null>(null),[error,setError]=useState(''),[taskIndex,setTaskIndex]=useState(0),[stepIndex,setStepIndex]=useState(0);
  const [callModel,setCallModel]=useState<ReturnType<typeof buildCalls>|null>(null),[view,setView]=useState(()=>window.location.hash==='#/graph'?'graph':'dashboard');
  useEffect(()=>{const route=()=>setView(window.location.hash==='#/graph'?'graph':'dashboard');window.addEventListener('hashchange',route);return()=>window.removeEventListener('hashchange',route);},[]);
  function navigate(destination:'graph'|'dashboard'){window.location.hash=`/${destination}`;setView(destination);}
  const [scale,setScale]=useState(()=>Math.min(1,window.innerWidth/1366,window.innerHeight/768));
  useEffect(()=>{const resize=()=>setScale(Math.min(1,window.innerWidth/1366,window.innerHeight/768));window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
  useEffect(()=>{const abort=new AbortController();fetch('./run.json',{signal:abort.signal}).then(response=>{if(!response.ok)throw Error('The run could not be loaded.');return response.json();}).then(archive=>{setDashboard(buildDashboard(archive) as Dashboard);setCallModel(buildCalls(archive));}).catch(e=>{if(e.name!=='AbortError')setError('The PathMNIST dashboard is unavailable. Please reload the page or restart the local server.');});return()=>abort.abort();},[]);
  const task=dashboard?.tasks[taskIndex],step=task?.pages[stepIndex];
  useEffect(()=>{if(view!=='dashboard')return;const key=(event:KeyboardEvent)=>{if(!task||event.altKey||event.ctrlKey||event.metaKey)return;if(event.key==='ArrowRight'){event.preventDefault();setStepIndex(i=>Math.min(task.pages.length-1,i+1));}else if(event.key==='ArrowLeft'){event.preventDefault();setStepIndex(i=>Math.max(0,i-1));}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[task,view]);
  if(!dashboard||!task||!step)return <div className="loading-screen"><Activity size={28}/><h1>PathMNIST</h1><p role={error?'alert':'status'}>{error||'Preparing the run dashboard…'}</p></div>;
  if(view==='graph'&&callModel)return <div className="dashboard graph-shell" style={{...(scale<1?{width:1366,height:768,transform:`scale(${scale})`,transformOrigin:'top left',margin:0}:{})} as React.CSSProperties}><CallGraph tasks={dashboard.tasks} model={callModel} onBack={()=>navigate('dashboard')} onOpenTask={id=>{setTaskIndex(dashboard.tasks.findIndex(t=>t.id===id));setStepIndex(0);navigate('dashboard');}}/></div>;
  const Icon=icons[task.id]??Activity;
  return <div className="dashboard" style={{'--selected':task.color,...(scale<1?{width:1366,height:768,transform:`scale(${scale})`,transformOrigin:'top left',margin:0}:{})} as React.CSSProperties}>
    <header className="topbar"><div className="brand"><span className="brand-icon"><GitBranch size={21}/></span><div><span className="eyebrow">AGENTIC MEDMNIST</span><h1>PathMNIST <span>/ Run dashboard</span></h1></div></div><div className="run-identity"><button className="graph-link" onClick={()=>navigate('graph')}><GitBranch size={14}/> Agent call graph</button><span>08 OCT 2026</span><span>SEED {dashboard.seed}</span><span className="run-status"><Check size={12}/> Run completed</span></div></header>
    <section className="kpis" aria-label="Run statistics"><Kpi label="SELECTED MODEL" value={dashboard.selected} detail="Validation-selected checkpoint"/><Kpi label="EXPERIMENTS" value={String(dashboard.stats.trials)} detail={`${dashboard.stats.decisions} recorded decisions`}/><Kpi label="VALIDATION ACCURACY" value={percent(dashboard.stats.validation)} detail="Saved checkpoint · same-center split"/><Kpi label="TEST ACCURACY" value={percent(dashboard.stats.test)} detail="Held-out · separate-center split"/><Kpi label="HUMAN REVIEW" value={dashboard.stats.review.toLocaleString('en-US')} detail="30.72% of test images"/></section>
    <div className="workspace">
      <aside className="agents-panel"><div className="section-heading"><div><span className="eyebrow">THE TEAM</span><h2>Agents & tasks</h2></div><span className="count">14</span></div><div className="agent-grid" aria-label="Select an agent task">{dashboard.tasks.map((candidate,i)=>{const AgentIcon=icons[candidate.id]??Activity;return <button key={candidate.id} className={`agent-box ${i===taskIndex?'selected':''}`} aria-pressed={i===taskIndex} aria-label={candidate.name} style={{'--agent':candidate.color} as React.CSSProperties} onClick={()=>{setTaskIndex(i);setStepIndex(0);}}><div className="agent-box-top"><AgentIcon size={18}/><span className="agent-status"><Check size={10}/> {contributionStatus(candidate.status)}</span></div><strong>{candidate.name}</strong><div className="agent-box-bottom"><span>{candidate.role}</span><ChevronRight size={12}/></div></button>;})}</div><div className="team-note"><span className="tiny-dot"/> Contributions to a completed run</div></aside>
      <main className="task-panel" aria-label="Task description"><div className="task-heading"><div className="task-symbol"><Icon size={24}/></div><div><span className="eyebrow">{task.role.toUpperCase()}</span><h2>{task.name}</h2></div><span className="task-status">{contributionStatus(task.status)}</span></div>
        <div className="step-content" key={`${task.id}-${stepIndex}`}><div className="step-title"><span className="step-kind">{step.view==='statistics'?'RESULTS & STATISTICS':step.view==='chart'?'TRAINING PERFORMANCE':'TASK BRIEF'}</span><h3>{step.title}</h3></div>
          {step.view==='statistics'?<><p className="results-intro">{step.outcome}</p><div className="table-container"><table><thead><tr>{step.table!.columns.map(column=><th key={column} scope="col">{column}</th>)}</tr></thead><tbody>{step.table!.rows.map((row,i)=><tr key={i} className={row[0].includes('★')?'winner-row':''}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></>:step.view==='chart'?<><p className="results-intro">{step.outcome}</p><div className="training-chart" role="img" aria-label="Selected model validation accuracy by training epoch"><ResponsiveContainer width="100%" height="100%"><AreaChart data={step.chart} margin={{left:5,right:20,bottom:8,top:15}}><defs><linearGradient id="curve-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={task.color} stopOpacity={0.3}/><stop offset="100%" stopColor={task.color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#242424" vertical={false}/><XAxis dataKey="epoch" stroke="#999" tickLine={false} axisLine={false} fontSize={11} label={{value:'Training epoch',position:'insideBottom',offset:-5,fill:'#999',fontSize:11}}/><YAxis domain={[0.96,1]} stroke="#999" tickLine={false} axisLine={false} tickFormatter={v=>percent(v,0)} fontSize={11}/><Tooltip contentStyle={{background:'#101010',border:'1px solid #444',borderRadius:10}} labelFormatter={v=>`Epoch ${v}`} formatter={v=>[percent(Number(v),3),'Validation accuracy']}/><Area type="monotone" dataKey="val_accuracy" stroke={task.color} strokeWidth={2} fill="url(#curve-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></>:<div className="brief-grid"><Narrative number="01" label="The objective" text={step.goal}/><Narrative number="02" label="The decision" text={step.choice}/><Narrative number="03" label="What happened" text={step.outcome}/></div>}
          {step.note&&<div className="interpretation"><span>KEEP IN MIND</span><p>{step.note}</p></div>}
        </div>
        <nav className="step-navigation" aria-label="Task steps"><button aria-label="Previous step" disabled={stepIndex===0} onClick={()=>setStepIndex(i=>i-1)}><ArrowLeft size={17}/> Previous</button><div className="step-position"><div className="step-dots" aria-hidden="true">{task.pages.map((_,i)=><span key={i} className={i===stepIndex?'current':i<stepIndex?'past':''}/>)}</div><span>Step <strong>{stepIndex+1}</strong> of {task.pages.length}</span></div><button aria-label="Next step" disabled={stepIndex===task.pages.length-1} onClick={()=>setStepIndex(i=>i+1)}>Next <ArrowRight size={17}/></button></nav>
      </main>
    </div>
    <footer><span><span className="tiny-dot"/> One run. Every choice in context.</span><span>Choose an agent <span className="footer-divider">/</span> Navigate with <kbd>←</kbd> <kbd>→</kbd></span><span>Single seed · Validation-only model selection</span></footer>
  </div>;
}
function Kpi({label,value,detail}:{label:string;value:string;detail:string}){return <div className="kpi"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;}
function Narrative({number,label,text}:{number:string;label:string;text:string}){return <section className="narrative"><div className="narrative-label"><span>{number}</span><h4>{label}</h4></div><p>{text}</p></section>;}
const root=document.getElementById('root');if(root)createRoot(root).render(<React.StrictMode><App/></React.StrictMode>);
